#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env}"
SECRETS_DIR="${SECRETS_DIR:-$ROOT_DIR/secrets}"
COMPOSE_FILE="${COMPOSE_FILE:-$SCRIPT_DIR/docker-compose.yml}"

: "${AWS_REGION:=ap-south-1}"
: "${BACKEND_REPOSITORY:=hariharibol-backend}"
: "${ADMIN_REPOSITORY:=hariharibol-admin}"
: "${IMAGE_TAG:=latest}"
: "${API_MEMORY_LIMIT:=512m}"
: "${WORKER_MEMORY_LIMIT:=512m}"
: "${SOCKET_MEMORY_LIMIT:=256m}"
: "${DEEPLINK_MEMORY_LIMIT:=256m}"
: "${ADMIN_MEMORY_LIMIT:=256m}"
: "${POSTGRES_MEMORY_LIMIT:=512m}"
: "${REDIS_MEMORY_LIMIT:=256m}"
: "${API_CPU_LIMIT:=1.0}"
: "${WORKER_CPU_LIMIT:=1.0}"
: "${SOCKET_CPU_LIMIT:=0.5}"
: "${DEEPLINK_CPU_LIMIT:=0.5}"
: "${ADMIN_CPU_LIMIT:=0.5}"
: "${POSTGRES_CPU_LIMIT:=1.0}"
: "${REDIS_CPU_LIMIT:=0.5}"

export AWS_REGION BACKEND_REPOSITORY ADMIN_REPOSITORY IMAGE_TAG
export API_MEMORY_LIMIT WORKER_MEMORY_LIMIT SOCKET_MEMORY_LIMIT DEEPLINK_MEMORY_LIMIT ADMIN_MEMORY_LIMIT
export POSTGRES_MEMORY_LIMIT REDIS_MEMORY_LIMIT
export API_CPU_LIMIT WORKER_CPU_LIMIT SOCKET_CPU_LIMIT DEEPLINK_CPU_LIMIT ADMIN_CPU_LIMIT POSTGRES_CPU_LIMIT REDIS_CPU_LIMIT
export ENV_FILE SECRETS_DIR COMPOSE_FILE
COMPOSE=(docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE")
